#
development:
  adapter: postgresql
  database: db/lsgtrack_development
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: db/lsgtrack_test
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/lsgtrack_production
  username: postgres
  password: admin
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

cucumber:
  <<: *test